### ISSUE TITLE
im.open returned an error

### ISSUE THREAD

**Issue by chad-upton** [litaio/lita-slack#87]
Using master as my gem.
No optional configs set.

```
[2016-03-28 20:45:56 UTC] ERROR: Lita::Handlers::Ai crashed. The exception was:
Slack API call to im.open returned an error: cannot_dm_bot.
Full backtrace:
/usr/local/rvm/gems/ruby-2.2.3/bundler/gems/lita-slack-38a968fd88e4/lib/lita/adapters/slack/api.rb:99:in `call_api'
/usr/local/rvm/gems/ruby-2.2.3/bundler/gems/lita-slack-38a968fd88e4/lib/lita/adapters/slack/api.rb:24:in `im_open'
/usr/local/rvm/gems/ruby-2.2.3/bundler/gems/lita-slack-38a968fd88e4/lib/lita/adapters/slack/im_mapping.rb:23:in `block in im_for'
/usr/local/rvm/gems/ruby-2.2.3/bundler/gems/lita-slack-38a968fd88e4/lib/lita/adapters/slack/im_mapping.rb:22:in `fetch'
/usr/local/rvm/gems/ruby-2.2.3/bundler/gems/lita-slack-38a968fd88e4/lib/lita/adapters/slack/im_mapping.rb:22:in `im_for'
/usr/local/rvm/gems/ruby-2.2.3/bundler/gems/lita-slack-38a968fd88e4/lib/lita/adapters/slack/rtm_connection.rb:36:in `im_for'
/usr/local/rvm/gems/ruby-2.2.3/bundler/gems/lita-slack-38a968fd88e4/lib/lita/adapters/slack.rb:65:in `channel_for'
/usr/local/rvm/gems/ruby-2.2.3/bundler/gems/lita-slack-38a968fd88e4/lib/lita/adapters/slack.rb:43:in `send_messages'
/usr/local/rvm/gems/ruby-2.2.3/gems/lita-4.7.0/lib/lita/robot.rb:129:in `send_messages'
/usr/local/rvm/gems/ruby-2.2.3/gems/lita-ai-0.1.1/lib/lita/handlers/ai.rb:13:in `chat'
/usr/local/rvm/gems/ruby-2.2.3/gems/lita-4.7.0/lib/lita/callback.rb:31:in `public_send'
/usr/local/rvm/gems/ruby-2.2.3/gems/lita-4.7.0/lib/lita/callback.rb:31:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/lita-4.7.0/lib/lita/handler/event_router.rb:61:in `block in trigger'
/usr/local/rvm/gems/ruby-2.2.3/gems/lita-4.7.0/lib/lita/handler/event_router.rb:59:in `map'
/usr/local/rvm/gems/ruby-2.2.3/gems/lita-4.7.0/lib/lita/handler/event_router.rb:59:in `trigger'
/usr/local/rvm/gems/ruby-2.2.3/gems/lita-4.7.0/lib/lita/robot.rb:183:in `block in trigger'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/set.rb:283:in `each_key'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/set.rb:283:in `each'
/usr/local/rvm/gems/ruby-2.2.3/gems/lita-4.7.0/lib/lita/robot.rb:180:in `trigger'
/usr/local/rvm/gems/ruby-2.2.3/gems/lita-4.7.0/lib/lita/robot.rb:72:in `receive'
/usr/local/rvm/gems/ruby-2.2.3/bundler/gems/lita-slack-38a968fd88e4/lib/lita/adapters/slack/message_handler.rb:122:in `dispatch_message'
/usr/local/rvm/gems/ruby-2.2.3/bundler/gems/lita-slack-38a968fd88e4/lib/lita/adapters/slack/message_handler.rb:162:in `handle_message'
/usr/local/rvm/gems/ruby-2.2.3/bundler/gems/lita-slack-38a968fd88e4/lib/lita/adapters/slack/message_handler.rb:18:in `handle'
/usr/local/rvm/gems/ruby-2.2.3/bundler/gems/lita-slack-38a968fd88e4/lib/lita/adapters/slack/rtm_connection.rb:100:in `block in receive_message'
/usr/local/rvm/gems/ruby-2.2.3/bundler/gems/lita-slack-38a968fd88e4/lib/lita/adapters/slack/event_loop.rb:10:in `block in defer'
/usr/local/rvm/gems/ruby-2.2.3/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in `call'
/usr/local/rvm/gems/ruby-2.2.3/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
```

Works fine if I just use the gem from rubygems.org.  Unfortunately the optional parse options weren't available from there so tried out master.

**Comment by eligiblekeng** [comment]
btw if you proceed despite the error and use the bot, it will still work just fine. Note sure that triggers the error, and it's inconsistent - happens sometimes; gone after restarting the computer.

**Comment by ekilah** [comment]
also seeing this on a fresh lita install, no changes made yet besides adding redis configs. it didn't happen the first ~2 times I started lita, then after that it comes up on every start

**Comment by ekilah** [comment]
https://github.com/seedalpha/slackbot/commit/0c790fe9d8615d010f7322fab21ca792692ae5f8 references the same error, it probably is easily fixed

**Comment by jimmycuadra** [comment]
Are you all still seeing this problem? I'm betting it was addressed by the recent fix to stop Lita from receiving other bot messages.

**Comment by eligiblekeng** [comment]
I don't see it anymore.

**Comment by liashukvladyslav** [comment]
Actually can confirm this problem present on 1.8.0 version
